# Generated by Django 4.1.3 on 2022-11-16 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pleasure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, verbose_name='Título')),
                ('img1', models.ImageField(upload_to='about', verbose_name='Imagen 1')),
                ('img2', models.ImageField(upload_to='about', verbose_name='Imagen 2')),
                ('img3', models.ImageField(upload_to='about', verbose_name='Imagen 3')),
            ],
            options={
                'verbose_name': 'Gusto',
                'verbose_name_plural': 'Gustos',
            },
        ),
    ]
