# Generated by Django 4.1.3 on 2022-11-17 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AboutApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pleasure',
            name='img1',
        ),
        migrations.RemoveField(
            model_name='pleasure',
            name='img2',
        ),
        migrations.RemoveField(
            model_name='pleasure',
            name='img3',
        ),
        migrations.AddField(
            model_name='pleasure',
            name='img',
            field=models.ImageField(default=None, upload_to='about', verbose_name='Imagen'),
        ),
    ]
