# Generated by Django 4.1.3 on 2022-11-17 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AboutApp', '0002_remove_pleasure_img1_remove_pleasure_img2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pleasure',
            name='img',
            field=models.ImageField(default=None, null=True, upload_to='about', verbose_name='Imagen'),
        ),
    ]
