# Generated by Django 4.1.3 on 2022-11-17 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GalleryApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='wide',
            field=models.BooleanField(default=False, verbose_name='Imagen ancha'),
        ),
    ]
